apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{ printf "environments/secrets.%s.yaml" .Values.namespace | .Files.Get | indent 2 }}


